---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  content/podcast:
    default_front_matter_template: podcast
  content/blog:
    default_front_matter_template: blog
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.28'
