---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/podcast
  label: Podcast
  create: all
  match: "**/*"
- type: directory
  path: content/assets
  label: Assets
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.26'
