---
hide_body: false
is_partial: false
fields:
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: linktitle
  label: Linktitle
  type: text
  hidden: false
  default: ''
- name: featured
  label: Featured
  type: text
  hidden: false
  default: ''
- name: featuredpath
  label: Featuredpath
  type: text
  hidden: false
  default: ''
- name: featuredalt
  label: Featuredalt
  type: text
  hidden: false
  default: ''
